### ISSUE TITLE
TypeError: mime.lookup is not a function

### ISSUE THREAD

**Issue by pyritepirate** [decentraland/web#24]
When trying to access old or any dummy pages after `/`, for example https://decentraland.org/contest
```TypeError: mime.lookup is not a function
    at lookup_type (/home/nowuser/src/node_modules/express-negotiate/lib/express-negotiate.js:110:21)
    at /home/nowuser/src/node_modules/express-negotiate/lib/express-negotiate.js:122:51
    at Array.forEach (<anonymous>)
    at parseHandlers (/home/nowuser/src/node_modules/express-negotiate/lib/express-negotiate.js:118:29)
    at IncomingMessage.request.negotiate (/home/nowuser/src/node_modules/express-negotiate/lib/express-negotiate.js:71:35)
    at /home/nowuser/src/server.js:153:7
    at Layer.handle_error (/home/nowuser/src/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/home/nowuser/src/node_modules/express/lib/router/index.js:315:13)
    at /home/nowuser/src/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/nowuser/src/node_modules/express/lib/router/index.js:335:12)
    at next (/home/nowuser/src/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle [as handle_request] (/home/nowuser/src/node_modules/express/lib/router/layer.js:97:5)
    at trim_prefix (/home/nowuser/src/node_modules/express/lib/router/index.js:317:13)
    at /home/nowuser/src/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/nowuser/src/node_modules/express/lib/router/index.js:335:12)
    at next (/home/nowuser/src/node_modules/express/lib/router/index.js:275:10)```

**Comment by pyritepirate** [comment]
You've got a new website now, so this is no longer an issue. Closing...
